language: elixir
elixir:
  - '1.5.1'
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWD";
    docker build -t phaelar/eatwhere:latest .;
    docker push phaelar/eatwhere:latest;
    fi
notifications:
  email: false
